Item.create(amount_cents: 799, name: 'Dune')
Item.create(amount_cents: 2600, name: 'Armada - Preorder')
Item.create(amount_cents: 1400, name: 'Ready Player One', max_quantity: 20, allow_multiple: true)
foundation = Item.create(name: 'Foundation Trilogy')
foundation.item_variations.create(amount_cents: 2825, name: 'Hardcover', allow_multiple: true)
foundation.item_variations.create(amount_cents: 1708, name: 'Paperback', allow_multiple: true)
